#!/usr/bin/env sh

# Fake slant_puzzle for testing the server go on local

echo '{'
echo '  "width": 10,'
echo '  "height": 5,'
echo '  "difficulty": "Hard",'
echo '  "problem": "a11e1e33b123b23b212d21a1a1a11b21213c2i01a",'
echo '  "solution": "\\\////\\/////\/\\\\//\/\////\///\\\/\//\\/\/\//\\",'
echo '  "have": "fun"'
echo '}'
