version: "3"
services:
  puzzle:
    image: slant_puzzle:latest
    build:
      context: ./puzzles
      dockerfile: dev.Dockerfile
    ports:
      - "5001:5001"
  puzzle_go:
    image: slant_puzzle_go:latest
    build:
      context: ./puzzles
      dockerfile: dev.go.Dockerfile
    ports:
      - "5002:5002"
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    image: slant_client:latest
    volumes:
      - ./client/src:/srv/src
      - ./client/public:/srv/public
    ports:
      - "3000:3000"
    # Needed for the dev environment to starts
    stdin_open: true
  async:
    image: slant_async:latest
    build:
      context: ./async
      dockerfile: dev.Dockerfile
    volumes:
      - ./async/server:/srv/server
    ports:
      - "8081:8081"
  server:
    image: slant_server:latest
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/slant_server:/srv/slant_server
    ports:
      - "5000:5000"
  nginx:
    image: slant_nginx:dev
    build:
      context: ./deployment
      dockerfile: nginx.prod.Dockerfile
    ports:
      - "80:80"
