version: "3"
services:
  puzzle:
    image: slant_puzzle_go:dev
    build:
      context: ./puzzles
      dockerfile: dev.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./puzzles/puzzle_service:/srv
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    image: slant_client:dev
    volumes:
      - ./client/src:/srv/src
      - ./client/public:/srv/public
    ports:
      - "3000:3000"
    # Needed for the dev environment to starts
    stdin_open: true
  server:
    image: slant_server:dev
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/server:/srv/server
      - ./db:/db
    ports:
      - "8081:8081"
  nginx:
    image: slant_nginx:dev
    build:
      context: ./deployment
      dockerfile: nginx.prod.Dockerfile
    ports:
      - "80:80"
