version: "3"
services:
  puzzle:
    image: slant_puzzle:prod
    ports:
      - "5001:5001"
  client:
    image: slant_client:prod
    ports:
      - "3000:3000"
  server:
    image: slant_server:prod
    ports:
      - "5000:5000"
  nginx:
      image: slant_nginx:prod
      ports:
        - "80:80"
